### ISSUE TITLE
Thank you VERY MUCH!

### ISSUE THREAD

**Issue by ejabu** [DaniGuardiola/pencil-material-template#3]
I did spent last three days to search simple prototyping tools in Linux.

I used Pencil before, but I didn't like how the presentation Mode was.

It was only simple HTML Export.

Since then, I searched full-offline tools, as I want to put many sketches into clickable prototype.

Finally I got your Export template! I never knew it can be customized like that

Thanks for the demo, thanks for sharing the export Template

**Comment by DaniGuardiola** [comment]
You are welcome :)
